workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: "15.1"
      cocoapods: default
      vars:
          XCODE_PROJECT: "Restaurant2.xcodeproj" # Isikan nama project Anda.
          XCODE_SCHEME: "Restaurant2" # Isikan nama scheme project Anda.
    scripts: 
      - name: Run tests
        script: |
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=16.1' \
          clean build test CODE_SIGNING_REQUIRED=NO
      - name: Build debug app
        script: |
          xcodebuild build-for-testing \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | tee xcodebuild.log test-without-building
    artifacts:
          - $$HOME/Library/Developer/Xcode/DerivedData/**/*.app
    publishing:
      email:
        recipients:
          - monicasucianto123@gmail.com 
